// Code generated by protoc-gen-go.
// source: protos/golang.conradwood.net/apis/commondeploy/commondeploy.proto
// DO NOT EDIT!

/*
Package commondeploy is a generated protocol buffer package.

It is generated from these files:
	protos/golang.conradwood.net/apis/commondeploy/commondeploy.proto

It has these top-level messages:
	MkenvRequest
	MkenvResponse
	CacheRequest
	CacheEntry
	DerivedCacheEntry
	ContainerDef
*/
package commondeploy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "golang.conradwood.net/apis/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// message to make an environment, e.g. prep chroots
type MkenvRequest struct {
	RootFileSystemID string `protobuf:"bytes,1,opt,name=RootFileSystemID" json:"RootFileSystemID,omitempty"`
	TargetDirectory  string `protobuf:"bytes,2,opt,name=TargetDirectory" json:"TargetDirectory,omitempty"`
}

func (m *MkenvRequest) Reset()                    { *m = MkenvRequest{} }
func (m *MkenvRequest) String() string            { return proto.CompactTextString(m) }
func (*MkenvRequest) ProtoMessage()               {}
func (*MkenvRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MkenvRequest) GetRootFileSystemID() string {
	if m != nil {
		return m.RootFileSystemID
	}
	return ""
}

func (m *MkenvRequest) GetTargetDirectory() string {
	if m != nil {
		return m.TargetDirectory
	}
	return ""
}

type MkenvResponse struct {
}

func (m *MkenvResponse) Reset()                    { *m = MkenvResponse{} }
func (m *MkenvResponse) String() string            { return proto.CompactTextString(m) }
func (*MkenvResponse) ProtoMessage()               {}
func (*MkenvResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CacheRequest struct {
	URL string `protobuf:"bytes,1,opt,name=URL" json:"URL,omitempty"`
}

func (m *CacheRequest) Reset()                    { *m = CacheRequest{} }
func (m *CacheRequest) String() string            { return proto.CompactTextString(m) }
func (*CacheRequest) ProtoMessage()               {}
func (*CacheRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CacheRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type CacheEntry struct {
	CachedURL           string               `protobuf:"bytes,1,opt,name=CachedURL" json:"CachedURL,omitempty"`
	Downloading         bool                 `protobuf:"varint,2,opt,name=Downloading" json:"Downloading,omitempty"`
	DownloadStarted     uint32               `protobuf:"varint,3,opt,name=DownloadStarted" json:"DownloadStarted,omitempty"`
	Downloaded          bool                 `protobuf:"varint,4,opt,name=Downloaded" json:"Downloaded,omitempty"`
	DownloadedTimestamp uint32               `protobuf:"varint,5,opt,name=DownloadedTimestamp" json:"DownloadedTimestamp,omitempty"`
	LastError           string               `protobuf:"bytes,6,opt,name=LastError" json:"LastError,omitempty"`
	Failures            uint32               `protobuf:"varint,7,opt,name=Failures" json:"Failures,omitempty"`
	CacheDir            string               `protobuf:"bytes,8,opt,name=CacheDir" json:"CacheDir,omitempty"`
	DerivedEntries      []*DerivedCacheEntry `protobuf:"bytes,9,rep,name=DerivedEntries" json:"DerivedEntries,omitempty"`
	LastUsed            uint32               `protobuf:"varint,10,opt,name=LastUsed" json:"LastUsed,omitempty"`
}

func (m *CacheEntry) Reset()                    { *m = CacheEntry{} }
func (m *CacheEntry) String() string            { return proto.CompactTextString(m) }
func (*CacheEntry) ProtoMessage()               {}
func (*CacheEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CacheEntry) GetCachedURL() string {
	if m != nil {
		return m.CachedURL
	}
	return ""
}

func (m *CacheEntry) GetDownloading() bool {
	if m != nil {
		return m.Downloading
	}
	return false
}

func (m *CacheEntry) GetDownloadStarted() uint32 {
	if m != nil {
		return m.DownloadStarted
	}
	return 0
}

func (m *CacheEntry) GetDownloaded() bool {
	if m != nil {
		return m.Downloaded
	}
	return false
}

func (m *CacheEntry) GetDownloadedTimestamp() uint32 {
	if m != nil {
		return m.DownloadedTimestamp
	}
	return 0
}

func (m *CacheEntry) GetLastError() string {
	if m != nil {
		return m.LastError
	}
	return ""
}

func (m *CacheEntry) GetFailures() uint32 {
	if m != nil {
		return m.Failures
	}
	return 0
}

func (m *CacheEntry) GetCacheDir() string {
	if m != nil {
		return m.CacheDir
	}
	return ""
}

func (m *CacheEntry) GetDerivedEntries() []*DerivedCacheEntry {
	if m != nil {
		return m.DerivedEntries
	}
	return nil
}

func (m *CacheEntry) GetLastUsed() uint32 {
	if m != nil {
		return m.LastUsed
	}
	return 0
}

type DerivedCacheEntry struct {
	FileID    string `protobuf:"bytes,1,opt,name=FileID" json:"FileID,omitempty"`
	FileRef   string `protobuf:"bytes,2,opt,name=FileRef" json:"FileRef,omitempty"`
	Function  string `protobuf:"bytes,3,opt,name=Function" json:"Function,omitempty"`
	Deriving  bool   `protobuf:"varint,4,opt,name=Deriving" json:"Deriving,omitempty"`
	Completed bool   `protobuf:"varint,5,opt,name=Completed" json:"Completed,omitempty"`
	LastUsed  uint32 `protobuf:"varint,6,opt,name=LastUsed" json:"LastUsed,omitempty"`
}

func (m *DerivedCacheEntry) Reset()                    { *m = DerivedCacheEntry{} }
func (m *DerivedCacheEntry) String() string            { return proto.CompactTextString(m) }
func (*DerivedCacheEntry) ProtoMessage()               {}
func (*DerivedCacheEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DerivedCacheEntry) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *DerivedCacheEntry) GetFileRef() string {
	if m != nil {
		return m.FileRef
	}
	return ""
}

func (m *DerivedCacheEntry) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *DerivedCacheEntry) GetDeriving() bool {
	if m != nil {
		return m.Deriving
	}
	return false
}

func (m *DerivedCacheEntry) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *DerivedCacheEntry) GetLastUsed() uint32 {
	if m != nil {
		return m.LastUsed
	}
	return 0
}

type ContainerDef struct {
	ID  uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	URL string `protobuf:"bytes,2,opt,name=URL" json:"URL,omitempty"`
}

func (m *ContainerDef) Reset()                    { *m = ContainerDef{} }
func (m *ContainerDef) String() string            { return proto.CompactTextString(m) }
func (*ContainerDef) ProtoMessage()               {}
func (*ContainerDef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ContainerDef) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ContainerDef) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func init() {
	proto.RegisterType((*MkenvRequest)(nil), "commondeploy.MkenvRequest")
	proto.RegisterType((*MkenvResponse)(nil), "commondeploy.MkenvResponse")
	proto.RegisterType((*CacheRequest)(nil), "commondeploy.CacheRequest")
	proto.RegisterType((*CacheEntry)(nil), "commondeploy.CacheEntry")
	proto.RegisterType((*DerivedCacheEntry)(nil), "commondeploy.DerivedCacheEntry")
	proto.RegisterType((*ContainerDef)(nil), "commondeploy.ContainerDef")
}

func init() {
	proto.RegisterFile("protos/golang.conradwood.net/apis/commondeploy/commondeploy.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0xcb, 0x6e, 0x13, 0x31,
	0x14, 0x55, 0x92, 0x36, 0x4d, 0x6e, 0xd3, 0x07, 0x46, 0x42, 0x56, 0x85, 0x20, 0x9a, 0x0d, 0x81,
	0xc5, 0xa4, 0x82, 0x2f, 0x80, 0x4e, 0x8b, 0x2a, 0x95, 0x8d, 0xdb, 0x7e, 0x80, 0x19, 0xdf, 0x06,
	0x8b, 0x19, 0xdf, 0xc1, 0x76, 0x5a, 0x65, 0xcd, 0x47, 0xf1, 0x7b, 0xc8, 0xce, 0x3c, 0x92, 0x14,
	0x89, 0xd5, 0xcc, 0x39, 0xf7, 0x75, 0x7c, 0x1f, 0xf0, 0xb9, 0xb2, 0xe4, 0xc9, 0xcd, 0x17, 0x54,
	0x48, 0xb3, 0x48, 0x73, 0x32, 0x56, 0xaa, 0x27, 0x22, 0x95, 0x1a, 0xf4, 0x73, 0x59, 0x69, 0x37,
	0xcf, 0xa9, 0x2c, 0xc9, 0x28, 0xac, 0x0a, 0x5a, 0x6d, 0x81, 0x34, 0xc6, 0xb2, 0xc9, 0x26, 0x77,
	0x96, 0xfe, 0x37, 0x53, 0xfd, 0x59, 0x47, 0x27, 0x0a, 0x26, 0xdf, 0x7e, 0xa2, 0x79, 0x14, 0xf8,
	0x6b, 0x89, 0xce, 0xb3, 0x0f, 0x70, 0x2a, 0x88, 0xfc, 0x95, 0x2e, 0xf0, 0x76, 0xe5, 0x3c, 0x96,
	0xd7, 0x19, 0xef, 0x4d, 0x7b, 0xb3, 0xb1, 0x78, 0xc6, 0xb3, 0x19, 0x9c, 0xdc, 0x49, 0xbb, 0x40,
	0x9f, 0x69, 0x8b, 0xb9, 0x27, 0xbb, 0xe2, 0xfd, 0xe8, 0xba, 0x4b, 0x27, 0x27, 0x70, 0x54, 0x57,
	0x71, 0x15, 0x19, 0x87, 0xc9, 0x14, 0x26, 0x17, 0x32, 0xff, 0x81, 0x4d, 0xd9, 0x53, 0x18, 0xdc,
	0x8b, 0x9b, 0xba, 0x52, 0xf8, 0x4d, 0x7e, 0x0f, 0x00, 0xa2, 0xcb, 0xa5, 0xf1, 0x76, 0xc5, 0x5e,
	0xc3, 0x38, 0x22, 0xd5, 0xb9, 0x75, 0x04, 0x9b, 0xc2, 0x61, 0x46, 0x4f, 0xa6, 0x20, 0xa9, 0xb4,
	0x59, 0x44, 0x15, 0x23, 0xb1, 0x49, 0x05, 0xad, 0x0d, 0xbc, 0xf5, 0xd2, 0x7a, 0x54, 0x7c, 0x30,
	0xed, 0xcd, 0x8e, 0xc4, 0x2e, 0xcd, 0xde, 0x00, 0x34, 0x14, 0x2a, 0xbe, 0x17, 0x53, 0x6d, 0x30,
	0xec, 0x1c, 0x5e, 0x76, 0xe8, 0x4e, 0x97, 0xe8, 0xbc, 0x2c, 0x2b, 0xbe, 0x1f, 0xb3, 0xfd, 0xcb,
	0x14, 0xb4, 0xdf, 0x48, 0xe7, 0x2f, 0xad, 0x25, 0xcb, 0x87, 0x6b, 0xed, 0x2d, 0xc1, 0xce, 0x60,
	0x74, 0x25, 0x75, 0xb1, 0xb4, 0xe8, 0xf8, 0x41, 0x4c, 0xd2, 0xe2, 0x60, 0x8b, 0x8f, 0xcc, 0xb4,
	0xe5, 0xa3, 0x18, 0xd8, 0x62, 0xf6, 0x15, 0x8e, 0x33, 0xb4, 0xfa, 0x11, 0x55, 0xe8, 0x90, 0x46,
	0xc7, 0xc7, 0xd3, 0xc1, 0xec, 0xf0, 0xe3, 0xdb, 0x74, 0x6b, 0x49, 0x6a, 0x9f, 0xae, 0x95, 0x62,
	0x27, 0x2c, 0x14, 0x09, 0x6a, 0xee, 0x1d, 0x2a, 0x0e, 0x6b, 0x01, 0x0d, 0x4e, 0xfe, 0xf4, 0xe0,
	0xc5, 0xb3, 0x0c, 0xec, 0x15, 0x0c, 0xc3, 0x22, 0xb4, 0xab, 0x51, 0x23, 0xc6, 0xe1, 0x20, 0xfc,
	0x09, 0x7c, 0xa8, 0x17, 0xa1, 0x81, 0xf1, 0x91, 0x4b, 0x93, 0x7b, 0x4d, 0x26, 0xf6, 0x7d, 0x2c,
	0x5a, 0x1c, 0x6c, 0xb1, 0x44, 0x98, 0xdc, 0xba, 0xdd, 0x2d, 0x8e, 0x63, 0xa7, 0xb2, 0x2a, 0x30,
	0x0c, 0x6c, 0x3f, 0x1a, 0x3b, 0x62, 0x4b, 0xf9, 0x70, 0x47, 0xf9, 0x39, 0x4c, 0x2e, 0xc8, 0x78,
	0xa9, 0x0d, 0xda, 0x0c, 0x1f, 0xd8, 0x31, 0xf4, 0x6b, 0xbd, 0x7b, 0xa2, 0x7f, 0x9d, 0x35, 0x1b,
	0xd7, 0x6f, 0x37, 0xee, 0xcb, 0x7b, 0x78, 0x67, 0xd0, 0x6f, 0x5e, 0x4e, 0x7d, 0x4b, 0xe1, 0x78,
	0xb6, 0x9a, 0xfa, 0x7d, 0x18, 0x8f, 0xe7, 0xd3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x56,
	0x2e, 0xd1, 0xbf, 0x03, 0x00, 0x00,
}
